version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: translation
      MYSQL_USER: user
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - 3306:3306
